# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aland < Formula
  desc "Publish and fork artifacts from the terminal"
  homepage "https://artifact.land"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artifactland/aland/releases/download/v0.1.1/aland_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "6de255d716e8b4a64e442c4c353b456b7d609ee775ebfd11a44fdcccd62d80a6"

      define_method(:install) do
        bin.install "aland"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artifactland/aland/releases/download/v0.1.1/aland_0.1.1_Darwin_arm64.tar.gz"
      sha256 "199fc2a3a6890261ce4ed283814c8accae32bb46e3ef02694654a05911aef076"

      define_method(:install) do
        bin.install "aland"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artifactland/aland/releases/download/v0.1.1/aland_0.1.1_Linux_x86_64.tar.gz"
      sha256 "009dcd1f2e94748df47388810e18f5546c73f03996d6777d78aceb59ce3905e9"
      define_method(:install) do
        bin.install "aland"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artifactland/aland/releases/download/v0.1.1/aland_0.1.1_Linux_arm64.tar.gz"
      sha256 "456777e0ce5517789cfb67eafd066ad30f92f35af0b8450b8bcbdb3795f41c18"
      define_method(:install) do
        bin.install "aland"
      end
    end
  end

  test do
    system "#{bin}/aland", "version"
  end
end
