# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aland < Formula
  desc "Publish and fork artifacts from the terminal"
  homepage "https://artifact.land"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artifactland/aland/releases/download/v0.1.2/aland_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "2b0eabcc0700628a242789d5e9805cc7043377d4388f6b5abe9fdb094a9a4880"

      define_method(:install) do
        bin.install "aland"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artifactland/aland/releases/download/v0.1.2/aland_0.1.2_Darwin_arm64.tar.gz"
      sha256 "f6ecaf71c3fdfab349bb8dca8cf3d73e29c2e9a654c20b2f89d64121b1a5ee7d"

      define_method(:install) do
        bin.install "aland"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/artifactland/aland/releases/download/v0.1.2/aland_0.1.2_Linux_x86_64.tar.gz"
      sha256 "ba8d4af20cdc369deb5d4dbe28ddbe57556b59a4ab8ea7464f4f58d1f6d9a3ee"
      define_method(:install) do
        bin.install "aland"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artifactland/aland/releases/download/v0.1.2/aland_0.1.2_Linux_arm64.tar.gz"
      sha256 "2c55be09b724d6d7e6493b1dd685c63a86e5cacf4cf2910bf0732175c7a7093b"
      define_method(:install) do
        bin.install "aland"
      end
    end
  end

  test do
    system "#{bin}/aland", "version"
  end
end
