# This file was generated by GoReleaser. DO NOT EDIT.
cask "aland" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/artifactland/aland/releases/download/v#{version}/aland_#{version}_Darwin_x86_64.tar.gz"
      sha256 "64b1843a88204a684f758cb33c769953ad1eea14ba9a2c42629b107eef149359"
    end
    on_arm do
      url "https://github.com/artifactland/aland/releases/download/v#{version}/aland_#{version}_Darwin_arm64.tar.gz"
      sha256 "e897c500afda085ba8054c9507330cc5fa2a1692143a4d776cdf4c4d435534fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/artifactland/aland/releases/download/v#{version}/aland_#{version}_Linux_x86_64.tar.gz"
      sha256 "5852c02a81c579a85078b71a29964335e63862ae7efcf66c5683f1cf8c5f3298"
    end
    on_arm do
      url "https://github.com/artifactland/aland/releases/download/v#{version}/aland_#{version}_Linux_arm64.tar.gz"
      sha256 "1cae62078047cb34e9f99bb74a9c4e6848b7a0e0dd35b48efe343dbb7011fd89"
    end
  end

  name "aland"
  desc "Publish and fork artifacts from the terminal"
  homepage "https://artifact.land"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aland"

  # No zap stanza required

end
